name: Auto update README with roadmap.sh profile

on:
  workflow_dispatch:
  schedule:
    - cron: '27 2 4,18 * *' # Bi-weekly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Run python script
        run: python gen.py

      - name: Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update profile"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

